---
- name: tap font
  homebrew_tap:
    name: sanemat/font

- name: install packages
  homebrew:
    name:
      - unzip
      - python

- name: install Ricty
  homebrew:
    name: ricty
    install_options: with-powerline

- name: install configparser for Darwin
  pip:
    name: configparser
    executable: /usr/local/bin/pip

- name: copy fonts
  copy:
    src: /usr/local/opt/ricty/share/fonts/{{ item }}
    dest: ~/.fonts
  with_items:
    - Ricty-Regular.ttf
    - Ricty-Bold.ttf
  notify: font_reload

- name: copy powerline fonts
  copy:
    src: /usr/local/opt/ricty/share/fonts/Ricty Regular for Powerline.ttf
    dest: ~/.fonts/Ricty-Regular-Powerline.ttf
  notify: font_reload

- name: check nerd exist
  stat:
    path: ~/.fonts/Ricty-Regular-nerd-Powerline.ttf
  register: nerd

- name: clone nerd-fonts
  git:
    repo: https://github.com/reireias/nerd-fonts.git
    depth: 1
    update: no
    dest: /tmp/nerd-fonts
    version: patch
  when: not nerd.stat.exists

- name: exec font patch
  command: >
    fontforge -script /tmp/nerd-fonts/font-patcher ~/.fonts/Ricty-Regular-Powerline.ttf
    --fontawesome --fontlinux --octicons --pomicons --powerline --powerlineextra --no-progressbars --quiet
  args:
    chdir: /tmp/nerd-fonts
  when: not nerd.stat.exists

- name: copy nerd-font
  copy:
    src: "/tmp/nerd-fonts/Ricty Regular Nerd Font Plus Font Awesome Plus Octicons Plus Pomicons Plus Font Logos (Font Linux).ttf"
    dest: ~/.fonts/Ricty-Regular-nerd-Powerline.ttf
  when: not nerd.stat.exists
  notify: font_reload
