---
- name: tap font
  homebrew_tap:
    name: sanemat/font

- name: install packages
  homebrew:
    name:
      - unzip
      - python
      - forntforge

- name: install Ricty
  homebrew:
    name: ricty
    install_options: with-powerline

- name: install configparser for Darwin
  pip:
    name: configparser
    executable: /usr/local/bin/pip

- name: block
  block:
  - name: copy fonts
    copy:
      src: /usr/local/opt/ricty/share/fonts/{{ item }}
      dest: ~/.fonts
      mode: 0644
    with_items:
      - Ricty-Regular.ttf
      - Ricty-Bold.ttf
    notify: font_reload

  - name: copy powerline fonts
    copy:
      src: /usr/local/opt/ricty/share/fonts/Ricty Regular for Powerline.ttf
      dest: ~/.fonts/Ricty-Regular-Powerline.ttf
      mode: 0644
    notify: font_reload

  - name: check nerd exist
    stat:
      path: ~/.fonts/Ricty-Regular-nerd-Powerline.ttf
    register: nerd

  - name: clone nerd-fonts
    git:
      repo: https://github.com/ryanoasis/nerd-fonts.git
      depth: 1
      update: false
      dest: /tmp/nerd-fonts
      version: v3.0.2
    when: not nerd.stat.exists

  - name: exec font patch
    command: >
      python3 /tmp/nerd-fonts/font-patcher ~/.fonts/Ricty-Regular-Powerline.ttf
      --fontawesome --fontlinux --octicons --pomicons --powerline --powerlineextra --no-progressbars --quiet
    args:
      chdir: /tmp/nerd-fonts
    when: not nerd.stat.exists

  - name: copy nerd-font
    copy:
      src: "/tmp/nerd-fonts/Ricty Regular Nerd Font Plus Font Awesome Plus Octicons Plus Pomicons Plus Font Logos (Font Linux).ttf"
      dest: ~/.fonts/Ricty-Regular-nerd-Powerline.ttf
      mode: 0644
    when: not nerd.stat.exists
    notify: font_reload
  when: not ansible_check_mode
