---
- name: install packages for Debian
  apt:
    name:
      - fontforge
      - unzip
      - python3-fontforge
    update_cache: true
  become: true

- name: tap font
  homebrew_tap:
    name: sanemat/font

- name: install Ricty
  homebrew:
    name: ricty
    install_options: with-powerline

- name: create ~/.fonts
  file:
    path: ~/.fonts
    state: directory
    mode: 0755

- name: block
  block:
  - name: create temp directory
    tempfile:
      state: directory
      suffix: font
    register: tempdir

  - name: copy generated fonts
    copy:
      src: /home/linuxbrew/.linuxbrew/opt/ricty/share/fonts/{{ item }}
      dest: ~/.fonts
      mode: 0644
    with_items:
      - Ricty-Regular.ttf
      - Ricty-Bold.ttf
    notify: font_reload

  - name: check nerd exist
    stat:
      path: ~/.fonts/Ricty-Regular-nerd.ttf
    register: nerd

  - name: clone nerd-fonts
    git:
      repo: https://github.com/ryanoasis/nerd-fonts.git
      depth: 1
      update: false
      dest: /tmp/nerd-fonts
      version: patch
    when: not nerd.stat.exists

  - name: exec font patch
    command: >
      python3 /tmp/nerd-fonts/font-patcher ~/.fonts/Ricty-Regular.ttf
      --fontawesome --fontlinux --octicons --pomicons --powerline --powerlineextra --no-progressbars --quiet
    args:
      chdir: /tmp/nerd-fonts
    when: not nerd.stat.exists

  - name: copy nerd-font
    copy:
      src: "/tmp/nerd-fonts/Ricty Regular Nerd Font Plus Font Awesome Plus Octicons Plus Pomicons Plus Font Logos (Font Linux).ttf"
      dest: ~/.fonts/Ricty-Regular-nerd.ttf
      mode: 0644
    when: not nerd.stat.exists
    notify: font_reload

  - name: check powerline exist
    stat:
      path: ~/.fonts/Ricty-Regular-nerd-Powerline.ttf
    register: powerline
  when: not ansible_check_mode
