---
- name: Install packages for mise
  apt:
    name:
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libssl-dev
      - libsqlite3-dev
      - libffi-dev
      - git
      - bash
      - curl
      - gpg
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: Install mise via install script for Linux  # noqa: command-instead-of-module
  shell: |
    set -o pipefail
    curl https://mise.run | sh
  args:
    executable: /bin/bash
    creates: /usr/local/bin/mise
  become: true
  when:
    - ansible_facts['os_family'] == 'Debian'
    - not ansible_check_mode

- name: Install mise for Mac
  community.general.homebrew:
    name:
      - mise
  when: ansible_facts['os_family'] == 'Darwin'
