# travis
if [[ -f ~/.travis/travis.sh ]]; then
    source ~/.travis/travis.sh
fi

# asdf-vm
if [[ -f ~/.asdf/completions/asdf.bash ]]; then
    source ~/.asdf/completions/asdf.bash
fi

# aws
if [[ -f ~/.asdf/shims/aws_zsh_completer.sh ]]; then
    source "$(asdf which aws_zsh_completer.sh)"
fi

# kubectl
if command -v kubectl > /dev/null; then
    source <(kubectl completion zsh)
fi

# minikube
if command -v minikube > /dev/null; then
    source <(minikube completion zsh)
fi

# pip (generated by `pip completion --zsh`)
# shellcheck disable=SC1087,SC2086,SC2162,SC2207,SC2211
function _pip_completion {
  local words cword
  read -Ac words
  read -cn cword
  reply=( $( COMP_WORDS="$words[*]" \
             COMP_CWORD=$(( cword-1 )) \
             PIP_AUTO_COMPLETE=1 $words[1] 2>/dev/null ))
}
compctl -K _pip_completion pip

# npm (generated by `npm completion`)
# shellcheck disable=SC2034,SC2046,SC2162,SC2207,SC2219
if type complete &>/dev/null; then
  _npm_completion () {
    local words cword
    if type _get_comp_words_by_ref &>/dev/null; then
      _get_comp_words_by_ref -n = -n @ -n : -w words -i cword
    else
      cword="$COMP_CWORD"
      words=("${COMP_WORDS[@]}")
    fi

    local si="$IFS"
    IFS=$'\n' COMPREPLY=($(COMP_CWORD="$cword" \
                           COMP_LINE="$COMP_LINE" \
                           COMP_POINT="$COMP_POINT" \
                           npm completion -- "${words[@]}" \
                           2>/dev/null)) || return $?
    IFS="$si"
    if type __ltrim_colon_completions &>/dev/null; then
      __ltrim_colon_completions "${words[cword]}"
    fi
  }
  complete -o default -F _npm_completion npm
elif type compdef &>/dev/null; then
  _npm_completion() {
    local si=$IFS
    compadd -- $(COMP_CWORD=$((CURRENT-1)) \
                 COMP_LINE=$BUFFER \
                 COMP_POINT=0 \
                 npm completion -- "${words[@]}" \
                 2>/dev/null)
    IFS=$si
  }
  compdef _npm_completion npm
elif type compctl &>/dev/null; then
  _npm_completion () {
    local cword line point words si
    read -Ac words
    read -cn cword
    let cword-=1
    read -l line
    read -ln point
    si="$IFS"
    IFS=$'\n' reply=($(COMP_CWORD="$cword" \
                       COMP_LINE="$line" \
                       COMP_POINT="$point" \
                       npm completion -- "${words[@]}" \
                       2>/dev/null)) || return $?
    IFS="$si"
  }
  compctl -K _npm_completion npm
fi
