---
name: install

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  install:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: ./.github/actions/setup-ansible
      - name: install dotfiles
        run: make dotfiles
      - name: install dependencies
        run: make dependencies
      - name: install mise tools
        run: |
          eval "$(mise activate bash)"
          mise install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: run test
        run: |
          eval "$(mise activate bash)"
          make test
